#!/usr/bin/env perl

use strict; 
use warnings; 

use IO::Socket::INET;

my $port = 80;
my $socket = IO::Socket::INET->new( PeerAddr => 'localhost', PeerPort => $port, Proto => 'tcp');
if ($socket) {
    print "Running\n";
    $socket->close;
}
else {
    print "Not running\n";
}
